services:
  postgres:
    image: postgres:16-alpine
    container_name: nvs-tech-postgres
    restart: unless-stopped

    environment:
      PGDATABASE: ${PGDATABASE:-nvs_tech}
      PGUSER: ${PGUSER:-nvs_tech}
      PGPASSWORD: ${PGPASSWORD:-nvs_tech}

      POSTGRES_DB: ${PGDATABASE:-nvs_tech}
      POSTGRES_USER: ${PGUSER:-nvs_tech}
      POSTGRES_PASSWORD: ${PGPASSWORD:-nvs_tech}

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - nvs_tech_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PGUSER} -d $${PGDATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - nvs-tech-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nvs-tech-app
#    restart: unless-stopped

    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: ${PGDATABASE:-nvs_tech}
      PGUSER: ${PGUSER:-nvs_tech}
      PGPASSWORD: ${PGPASSWORD:-nvs_tech}
      HTTP_PORT: ${HTTP_PORT:-8888}

    ports:
      - "127.0.0.1:8888:8888"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - nvs-tech-network

volumes:
  nvs_tech_postgres_data:

networks:
  nvs-tech-network:
    driver: bridge
